# Generated by Django 3.1.1 on 2022-03-08 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object3d',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectId', models.CharField(max_length=100, verbose_name='object id')),
                ('label', models.CharField(max_length=100, verbose_name='object label')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containing', to='core.dataset', verbose_name='container')),
            ],
            options={
                'verbose_name': 'Object Name',
                'verbose_name_plural': 'Object Name',
            },
        ),
        migrations.CreateModel(
            name='Modality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalityType', models.IntegerField(choices=[(0, 'PointCloud'), (1, 'Voxel'), (2, 'MultiView')], verbose_name='modalityType')),
                ('uuid', models.CharField(max_length=100)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modality', to='core.object3d', verbose_name='host object')),
            ],
            options={
                'verbose_name': 'Modality',
                'verbose_name_plural': 'Modality',
            },
        ),
    ]
