# Generated by Django 3.1.1 on 2022-03-10 07:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modality',
            name='uuid',
        ),
        migrations.AddField(
            model_name='modality',
            name='path',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
